### ISSUE TITLE
ROADMAP 2019

### ISSUE THREAD

**Issue by maty21** [kube-HPC/hkube#207]
- [ ] PAAS 
- [ ] Resource allocation heuristic improvements (ML)
- [x] Worker affinity (GPU, specific node)
- [ ] Additional adapter for common orchestrators (spark&kubeflow)
- [x] Code API for pipeline creation - #190
- [ ] Cluster scaling ?
- [ ] Caching for algorithms (manually/input with hash )
- [ ] Developer IDE - allow for easy developing and debugging of algorithms  
- [ ] Streaming Pipelines
- [x] Hkube Dashboard  - embed Jaeger, Prometues, AirFlow
- [ ] More built in  storage support 
- [ ] Public algorithm store (helm like)
- [ ] Authentication & Authorization
- [x] Simplify API for adding algorithm to HKUBE
- [ ] abilty for runing subset of algorithm
- [x] Sub-pipeline support
- [ ] API for asking more resorces cloud providers
- [x] The other WaitAny
- [x] Pipeline Concurrency ?
- [ ] change algorithms hardware resource dynamically
- [x] add tracing api for algorithm
- [ ] minimum hot workers by default
