### ISSUE TITLE
roadmap in time amount section

### ISSUE THREAD

**Issue by maty21** [kube-HPC/hkube#253]
### **Infrastracture**  (3) 
- [ ] PAAS
- [ ] API for asking more resorces cloud providers
- [ ] simplify installtion
- [ ] Worker affinity (GPU, specific node)
- [ ] Public algorithm store (helm like)
- [ ] Authentication & Authorization

### **improve user experience**  (3) 
- [x] Code API for pipeline creation - #190
- [x] Developer IDE - allow for easy developing and debugging of algorithms  
- [ ] Caching for algorithms (manually/input with hash )
- [ ] Hkube Dashboard  Improvements
- [x] Simplify API for adding an algorithm to HKUBE(Algorithm builder)
- [x] Sub-pipeline support
- [x] add tracing API for algorithm
- [ ] ability for running pipelines from pipeline descriptor
- [ ] add /algorithm/apply to the Hkube API

### **performance improvments**  (2) 
- [x] minimum hot workers by default
- [ ] add caching layer for algorithms with small data transfer
- [ ] change algorithms hardware resource dynamically
- [ ] send algorithm to queue before pipeline finished
### **other** 
 - [ ]  Streaming Pipelines #263
 - [ ] Resource allocation heuristic improvements (ML)
-  [ ]  The other WaitAny
-  [x]  Integration with jupiter notebook
-  [ ]  kubeflow poc 
-  [x] pause job
-  [x] algorithm TTL
### algorithm builder
 - [x] start from other base

### refactoring
- [x] etcd client
- [ ] POC for moving to bear pods instead of jobs
- [ ] resource manager: add more metrics pipeline awareness and GPU
- [ ] update algorithm hardware requirements according to usage
- [ ] improve the site by adding information for new features and end to end example
