### ISSUE TITLE
Automatic build integration with git

### ISSUE THREAD

**Issue by golanha** [kube-HPC/hkube#506]
We would like to be able to progress algorithm versions along the progress of code in the algorithms code git repository.
We'd like to be able to register a hook on the git remote repository that will invoke building and updating an algorithm - upon git specific events.

- [ ] support building algorithm from git through rest.
- [ ] support through ui
- [ ] Webhook integration
- [ ] support git repository authentication
- [ ] support through cli

**Comment by tamir321** [comment]
# git hub and lab Test

File: algorithmBuild .js
describe: "git hub and git lab algorithm builds (git 506)"

misssing : repository authentication for gitlab and github

Test | description 
------|----------------
build github master algorithm|build github master algorithm
build github branch algorithm|build github branch algorithm
build gitlab master algorithm|build gitlab master algorithm
build gitlat branch algorithm|build gitlat branch algorithm
test webhook github (git 518)|test webhook github (git 518)
test webhook gitlab (git 518)|test webhook gitlab (git 518)
gitlab repository authentication| test gitlab repository authentication
github repository authentication|test github repository authentication
