### ISSUE TITLE
Dashboard v2 Roadmap

### ISSUE THREAD

**Issue by denvash** [kube-HPC/hkube#775]
# Dashboard v2

Another iteration for [simulator - web-based UI for HKube](https://github.com/kube-HPC/simulator).

Main building blocks:
- [Atomic Design](https://bradfrost.com/blog/post/atomic-web-design/)
- [Tailwind CSS](https://tailwindcss.com/)
- [Redux toolkit](https://redux-toolkit.js.org/)
- [Gatsby](https://www.gatsbyjs.com/)
- [Motion (Animations)](https://www.framer.com/api/motion/animation/)
- [React - UI Library](https://reactjs.org/docs/getting-started.html)

-----

- [Figma](https://www.figma.com/file/EcNSXgVU5MLRfdjLKh8Fdf/HKube-Dashboard?node-id=0%3A1) (Prototyping)
- [Repository](https://github.com/kube-HPC/dashboard) 

## Step 1 (POC)

Implementing the **Jobs view**.

- [x] Prototype UI view.
- [x] Virtual List.
- [x] Mounting animation, transitions, smoother feel.
- [x] Graph view
  - [x] Upgrading visual component (`vis-network`) to v7.
  - [x] Fast rendering using canvas references.
- [x] Job actions (on row)
  - [x] Rerun
  - [x] Play/Stop/Pause
- [x] Notification hub
- [x] Runnig job preview
- [x] Dark Theme
- [x] Responsive from tablet above.

## Step 2

- [x] Job logs
- [ ] Jobs tagging (?)
- [x] Filter
- [x] Search
- [ ] Error Boundary
- [x] Settings
  - [x] Select logs source
  - [x] Select graph direction
- [x] Experiments
- [x] Socket status
- [ ] Run raw pipeline
- [x] Errors Logs
- [x] Typing (flow)
