### ISSUE TITLE
data set management 

### ISSUE THREAD

**Issue by reggev** [kube-HPC/hkube#965]
## Description
This feature will enable managing data sources and applying them to pipelines

## Includes
- [x] a user can create a new data source entry on the app by uploading a new file and naming it
- [x] when creating a new pipeline, the user can select a data source by its name
- [x] a list of data sources for editing and deleting data sources
- [x] A CRUD API on the API-server
- [x] UI form for creating data sources
- [x] a table for managing the collection
- [x] update the adapters for the different languages to support this feature
- [x] add the relevant data to the polling object the UI uses
- [x] The data set's metadata is stored on MongoDB?

#### TODO:
- [x] update package `@hkube/parsers`.
- [x] Update package `@hkube/storage-manager`.
- [x] Add new package `@hkube/db`.
- [x] Update service Api-Server.
- [x] Update service `Pipeline-Driver`.
- [x] Run the full test case.
- [x] Implement UI.

### Add new datasource
POST /datasource
- Name: 'model/binyanim'
- Description <string>
- File: <binary> any file (if zip or .gz need to extract)

**Comment by reggev** [comment]
this feature will enable managing data sources and applying them to pipelines
### Includes
[ ] - a user can create a new data source entry on the app by uploading a new file and naming it
[ ] - when creating a new pipeline, the user can select a data source by its name
[ ] - a list of data sources for editing and deleting data sources
[ ] - A CRUD API on the API-server 
[ ] - UI form for creating data sources
[ ] - a table for managing the collection
[ ] - update the adapters for the different languages to support this feature
[ ] - add the relevant data to the polling object the UI uses
[ ] - The data set's metadata is stored on ETCD

### definitions
**Data source:**
Can a data source have multiple files under it?
File types? (including compressed files) 
Does it have a version number? 
Can I upload multiple files? 
**Metadata:**
who uploaded this file 
File description
Version description?
