### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by maty21** [kube-HPC/hkube#977]
- [x]  data set management
- [ ] Hkube hardware optimization
- [ ] Versions  updates
- [ ]  Users managment
- [x] mongoDB
- [ ] Bash command upload for builds
- [ ] .Net core builds
- [x] Dinamic MInimum resources
- [ ] Descriptions for running jobs 
- [ ] TensorBoard jobs selection 
- [ ] POC cli sync
- [ ] Tensorflow integration to run on multiple containers
- [ ] Management for local running 
- [ ] Use cloud resources integration with the cloud for getting mor machines
- [ ] Build from azure devops
- [x] UI wizard for pipeline building 
- [ ] Spark hadoop integration 
- [ ]  #972 
- [ ]  #973 
- [ ]  #974 
- [ ]  #253, 
- [ ]  #786
- [x]  #585
